exec: \
bmp_process_serial.c bmp_process_serial_modified.c bmp_process_parallel_v2.c
	gcc -o bmp_process_serial bmp_process_serial.c
	gcc -o bmp_process_serial_modified bmp_process_serial_modified.c
	gcc -o bmp_process_parallel_v2 bmp_process_parallel_v2.c
	echo "Compiling bmp_process_serial.c bmp_process_serial_modified.c bmp_process_parallel_v2"
	touch compile
